// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrmtrzxnfyfyyodspipl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhybXRyenhuZnlmeXlvZHNwaXBsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNzM5NzYsImV4cCI6MjA3NDc0OTk3Nn0.VHWzpnJXqqTQ3_wt3j5AHh7kGbqcznKt5QEiiGHiP3w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});