// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oguaxeiztwofmxaiidza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndWF4ZWl6dHdvZm14YWlpZHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2Njg3MzgsImV4cCI6MjA3NDI0NDczOH0.7xeNb9AuUtzTJPYAAzxNIN3pyHFbx_i1Aq9tNR_aZtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});